package citytrade.engine.command;

/** Why a command was rejected. */
public enum RejectionCode {
    INVALID_PHASE,
    UNKNOWN_PLAYER,
    OBJECTIVES_ALREADY_CHOSEN,
    INVALID_OBJECTIVE_CHOICE,
    OBJECTIVES_NOT_CHOSEN,
    INVALID_UPKEEP_PRIORITY,
    INVALID_QUANTITY,
    INSUFFICIENT_MONEY,
    INSUFFICIENT_RESOURCES,
    MARKET_BUY_LIMIT_EXCEEDED,
    MAX_LEVEL_REACHED,
    ALREADY_UPGRADED_THIS_ROUND,
    UNKNOWN_BUILDING,
    BUILDING_ALREADY_BUILT,
    LEVEL_TOO_LOW,
    INVALID_BUILDING_CHOICE
}
